### ISSUE TITLE
ONNX export problem. 

### ISSUE THREAD

**Issue by Byronnar** [feiyuhuahuo/SOLOv2_minimal#2]
Error info:
```

def get_seg_scripted(cate_list: list[torch.Tensor], kernel_list: list[torch.Tensor], seg_pred: torch.Tensor):
TypeError: 'type' object is not subscriptable
```
Could you please tell me how to export onnx model? Thanks

**Comment by feiyuhuahuo** [comment]
When exporting ONNX model, you should guarantee that the model do detect some masks from the input image. Or it will encounter an error in post-process. When inference with the exported ONNX model, you should use try-except to skip the inference error if the model do not detect any mask.

**Comment by Byronnar** [comment]
Ok, Thank you, I will try
